[build]
command = "react-scripts build"
functions = "netlify/functions"
publish = "build"

[[plugins]]
package = "/plugins/netlify-plugin-hypi"

[context.production.environment]
GATSBY_HYPI_DOMAIN = "rapacity.apps.hypi.appip"
REACT_APP_HYPI_DOMAIN = "rapacity.apps.hypi.appip"
VUE_APP_HYPI_DOMAIN = "rapacity.apps.hypi.appip"
NEXT_PUBLIC_HYPI_DOMAIN = "rapacity.apps.hypi.appip"
