[build]
command = "react-scripts build"
functions = "netlify/functions"
publish = "build"

[[plugins]]
package = "/plugins/netlify-plugin-hypi"

["build.environment"]
  GATSBY_HYPI_DOMAIN = "rapacity.apps.hypi.app"
  REACT_APP_HYPI_DOMAIN = "rapacity.apps.hypi.app"
  VUE_APP_HYPI_DOMAIN = "rapacity.apps.hypi.app"
  NEXT_PUBLIC_HYPI_DOMAIN = "rapacity.apps.hypi.app"
