[build]
command = "react-scripts build"
functions = "netlify/functions"
publish = "build"

[[plugins]]
package = "/plugins/netlify-plugin-hypi"

[[plugins]]
package = 'netlify-plugin-env'
  [plugins.inputs]
  mode = 'prefix'
  