[build]
  command = "react-scripts build"
  functions = "netlify/functions"
  publish = "build"

[context.production.environment]
  REACT_APP_HYPI_DOMAIN = "rapacity.apps.hypi.app"
  REACT_APP_HYPI_TOEKN = "eyJhbGciOiJSUzI1NiJ9.eyJoeXBpLmxvZ2luIjp0cnVlLCJoeXBpLnVzZXJuYW1lIjoiZW1hbi5jc2UyMDA4QGdtYWlsLmNvbSIsImh5cGkuZW1haWwiOiJlbWFuLmNzZTIwMDhAZ21haWwuY29tIiwiYXVkIjoiMDFGMkdaQkpLSDZSM1RDNkVKRFJFNU5IRzQiLCJpYXQiOjE2MjczNzY3MzcsImV4cCI6MTYyOTk2ODczNywic3ViIjoiMDFGMkdaQkpLQUgxSkNDQlZaUzI0TVQ3VlIiLCJuYmYiOjE2MjczNzY3Mzd9.6pDA8zIkTOdogkD2M7Ts_9LEZ-8gt19sBeAsRemZpgyJy4bu7PL2YJWn-pJWkeE7EllNMkx1gVapbYG3KC2xYy7JBMz67cg86LEquIYGdYJHvLiNr8-PBmqqREKkIOYZl2-gJfVaEzog4agXL5-d2RMGs_1PCsT7v640PWDHCwxkdKWe2e06B7ekJOnPUWTW1rCLEdMvG6ANlDnMQwJUUGx4mGx2GIVq1bVD9hKtE-s271Fnw3gHBsu-t_MEg1wfIW7dJiSi9VbBFbimt7pO7Y8tqd-GLYmxd4Sk_Q2npyjtzSL4YJoMp4nHaUf13umIQ-AHj4bkTBuqOBCQI26zug"
